# Generated by Django 4.1.3 on 2022-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, editable=False, max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='thing',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'archived'), _negated=True), fields=('name',), name='thing_unique_name'),
        ),
    ]
